#!/usr/bin/env perl
use v5.36;
use warnings;
no warnings 'utf8';
use FindBin qw($Bin);
use lib "$Bin", "$ENV{HOME}/.config/i3/scripts";
use I3Connect qw(i3_connect find_first_workspace);

my $STATE_FILE = "$ENV{HOME}/.config/i3/.layout-state";

my $i3 = i3_connect();
my $tree = $i3->get_tree->recv;

my $ws = find_first_workspace($tree);

my $scheme = 'split';
if ($ws) {
    my $child = ($ws->{nodes} // [])->[0];
    if ($child) {
        my $layout = $child->{layout} // '';
        $scheme = 'tabbed'  if $layout eq 'tabbed';
        $scheme = 'stacked' if $layout eq 'stacked';
        $scheme = 'split'   if $layout eq 'splith' || $layout eq 'splitv';
    }
}

open my $fh, '>', $STATE_FILE or die "Cannot write $STATE_FILE: $!\n";
print $fh "$scheme\n";
close $fh;

my %icons = (
    split   => "\x{eb56}",
    tabbed  => "\x{f00b}",
    stacked => "\x{f51e}",
);
print $icons{$scheme} // $icons{split};
print "\n";
