#!/usr/bin/env perl
use v5.36;
use warnings;
use FindBin qw($Bin);
use lib "$Bin";
use I3Connect qw(i3_connect);

my $direction = $ARGV[0] // 'next';
die "Usage: $0 [next|prev]\n" unless $direction eq 'next' || $direction eq 'prev';

my $i3 = i3_connect();
$i3->connect->recv or die "Failed to connect to i3";

my $workspaces = $i3->get_workspaces->recv;
my ($focused) = grep { $_->{focused} } @$workspaces;
exit unless $focused;

my $name = $focused->{name};
my ($num, $suffix) = $name =~ /^(\d+)([a-z])$/i;
exit unless defined $num && defined $suffix;

my $next_num = $direction eq 'next' ? $num + 1 : $num - 1;
$next_num = 1  if $next_num > 8;
$next_num = 8  if $next_num < 1;

my $target = "$next_num$suffix";
$i3->command("move container to workspace $target; workspace $target")->recv;
