#!/usr/bin/env perl
use v5.36;
use FindBin qw($Bin);
use lib "$Bin";
use I3Connect qw(i3_connect find_focused);

my $i3 = i3_connect();
my $tree = $i3->get_tree->recv;

my $focused = find_focused($tree);
exit 0 unless $focused;

if (($focused->{nodes} // [])->@*) {
    $i3->command('focus child')->recv;
}
else {
    $i3->command('focus parent')->recv;
}
