#!/usr/bin/env perl
use v5.36;
use FindBin qw($Bin);
use lib "$Bin";
use I3Connect qw(i3_connect);

my $i3 = i3_connect();
my $tree = $i3->get_tree->recv;

sub find_focused($node) {
    return $node if $node->{focused};
    for my $child (($node->{nodes} // [])->@*, ($node->{floating_nodes} // [])->@*) {
        my $found = find_focused($child);
        return $found if $found;
    }
    return undef;
}

my $focused = find_focused($tree);
exit 0 unless $focused;

if (($focused->{nodes} // [])->@*) {
    $i3->command('focus child')->recv;
}
else {
    $i3->command('focus parent')->recv;
}
