[colors]
background = '#303446'
foreground = '#c6d0f5'

cursor_bg = '#ca9ee6'
cursor_fg = '#303446'
cursor_border = '#ca9ee6'

selection_bg = '#542f79'
selection_fg = '#c6d0f5'

ansi = ['#292c3c', '#ff728a', '#73e68e', '#ffdc72', '#ba88da', '#542f79', '#ca9ee6', '#eae3f1']
brights = ['#625d67', '#ff9faf', '#a5ffbb', '#ffe8a5', '#e2b9fd', '#e9c7ff', '#f1dbff', '#fbf8ff']
