[colors]
background = '#303446'
foreground = '#c6d0f5'

cursor_bg = '#ef9f76'
cursor_fg = '#303446'
cursor_border = '#ef9f76'

selection_bg = '#6d3e24'
selection_fg = '#c6d0f5'

ansi = ['#292c3c', '#ff7670', '#8cef76', '#ffe570', '#e38759', '#6d3e24', '#ef9f76', '#faf1eb']
brights = ['#645e5b', '#ffa29e', '#b5ffa4', '#ffeea4', '#ffb691', '#ffc3a4', '#ffd8c4', '#fffaf8']
