[colors]
background = '#1a120e'
foreground = '#f0dfd8'

cursor_bg = '#ff6d00'
cursor_fg = '#1a120e'
cursor_border = '#ff6d00'

selection_bg = '#3e2723'
selection_fg = '#f0dfd8'

ansi = ['#1a120e', '#ff1d07', '#2cff00', '#ffd100', '#f26700', '#3e2723', '#ff6d00', '#ffe4e0']
brights = ['#4e3f3d', '#ff493f', '#6bff4c', '#ffdf4c', '#ff8226', '#ff984c', '#ffbd8c', '#fff4f2']
