[preferred]
#default=wlr;gtk;
# use kde by default
default=kde
# Keep using the reliable wlroots portal specifically for screencasting/OBS
org.freedesktop.impl.portal.ScreenCast=wlr
org.freedesktop.impl.portal.Screenshot=wlr
