[templates.dmsvscodedefault]
input_path = 'SHELL_DIR/matugen/templates/vscode-color-theme-default.json'
output_path = 'CONFIG_DIR/Code - OSS/User/dms-themes/dankshell-default.json'

[templates.dmsvscodedark]
input_path = 'SHELL_DIR/matugen/templates/vscode-color-theme-dark.json'
output_path = 'CONFIG_DIR/Code - OSS/User/dms-themes/dankshell-dark.json'

[templates.dmsvscodelight]
input_path = 'SHELL_DIR/matugen/templates/vscode-color-theme-light.json'
output_path = 'CONFIG_DIR/Code - OSS/User/dms-themes/dankshell-light.json'
