
###############################################################################
# menu                                                                        #
###############################################################################

# start dmenu (a program launcher)
#bindsym $mod+d exec --no-startup-id dmenu_run

# There also is i3-dmenu-desktop which only displays applications shipping a
# .desktop file. It is a wrapper around dmenu, so you need that installed.
bindsym $mod+d exec --no-startup-id i3-dmenu-desktop --dmenu="dmenu -nb '#1d2021' -nf '#ebdbb2' -sb '#d65d0e' -sf '#1d2021'"

# # A more modern dmenu replacement is rofi:
# #i3-dmenu-desktop --dmenu="rofi -dmenu -i -p 'apps'"
# bindsym $mod+d exec "rofi -modi drun,run -show drun"
# bindsym Ctrl+space exec --no-startup-id rofi -show run
# bindsym $alt+Tab exec --no-startup-id rofi -show window

# launch categorized menu
bindsym $mod+z exec --no-startup-id morc_menu


#####################################
# Application menu handled by rofi: #
#####################################

## rofi bindings fancy application menu ($mod+d /F9 optional disabled)

bindsym $mod+space exec --no-startup-id ~/.config/i3/scripts/rofi -modi drun -show drun -config ~/.config/i3/rofi/rofidmenu.rasi

## rofi bindings for window menu ($mod+t /F10 optional disabled)
bindsym $mod+Tab exec --no-startup-id ~/.config/i3/scripts/rofi -show window -config ~/.config/i3/rofi/rofidmenu.rasi
#bindsym $mod+Tab exec --no-startup-id ~/.config/i3/scripts/i3-window-switch

## keybinding helper (rofi)
bindsym $mod+Shift+question exec --no-startup-id ~/.config/i3/scripts/keybindings

## rofi bindings to manage clipboard (install rofi-greenclip from the AUR)

#exec --no-startup-id greenclip daemon>/dev/null
#bindsym $mod+c exec --no-startup-id rofi -modi "clipboard:greenclip print" -show clipboard \
#       -config ~/.config/rofi/rofidmenu.rasi

# Power Profiles menu switcher (rofi)
bindsym $mod+Shift+p exec --no-startup-id ~/.config/i3/scripts/power-profiles

###############################################################################
# Start Applications
###############################################################################

# bindsym $mod+Shift+Return exec thunar
# bindsym Ctrl+space exec --no-startup-id rofi -show run
# bindsym $alt+Tab exec --no-startup-id rofi -show window

# File managers
bindsym $mod+F1 exec dolphin
bindsym $mod+Shift+F1 exec pkexec dolphin

# Browsers
bindsym $mod+F2 exec brave --profile-directory='Default'
bindsym $mod+Shift+F2 exec brave --profile-directory='Default' --incognito
#bindsym $mod+F5 exec firefox
#bindsym $mod+Shift+F5 exec firefox --private-window

# gmail
bindsym $mod+F3 exec brave --app=https://mail.google.com/mail/u/0/#inbox --profile-directory='Default'

# toggle-tmux tmux sessions
bindsym $mod+F9  exec --no-startup-id ~/.config/i3/scripts/toggle-tmux --terminal kitty --session opencode --class kitty --title opencode --cmd opencode --maximized
bindsym $mod+F10 exec --no-startup-id ~/.config/i3/scripts/toggle-tmux --terminal kitty --session kilo     --class kitty --title kilo     --cmd kilo     --maximized
bindsym $mod+F11 exec --no-startup-id ~/.config/i3/scripts/toggle-tmux --terminal kitty --session monitor  --class kitty --title monitor  --cmd btop     --maximized
bindsym $mod+grave exec --no-startup-id ~/.config/i3/scripts/toggle-tmux --terminal kitty --session work      --class kitty --title work      --maximized

# quake-like drop-down terminal
#bindsym $mod+F12 exec --no-startup-id guake-toggle
bindsym $mod+F12 exec --no-startup-id yakuake

# bindsym $mod+F5 exec terminal -e 'mocp'
# bindsym $mod+Shift+d --release exec "killall dunst; exec notify-send 'restart dunst'"
