
###############################################################################
# menu                                                                        #
###############################################################################

# start dmenu (a program launcher)
#bindsym $mod+d exec --no-startup-id dmenu_run

# There also is i3-dmenu-desktop which only displays applications shipping a
# .desktop file. It is a wrapper around dmenu, so you need that installed.
#bindsym $mod+Shift+d exec --no-startup-id i3-dmenu-desktop --dmenu="dmenu -nb '#1d2021' -nf '#ebdbb2' -sb '#d65d0e' -sf '#1d2021'"
bindsym $mod+Shift+d exec --no-startup-id i3-dmenu-desktop --dmenu="rofi -dmenu -i -p 'apps'"

# # A more modern dmenu replacement is rofi:
# #i3-dmenu-desktop --dmenu="rofi -dmenu -i -p 'apps'"
# bindsym $mod+d exec "rofi -modi drun,run -show drun"
# bindsym Ctrl+space exec --no-startup-id rofi -show run
# bindsym $alt+Tab exec --no-startup-id rofi -show window

# launch categorized menu
bindsym $mod+z exec --no-startup-id morc_menu


#####################################
# Application menu handled by rofi: #
#####################################


## rofi bindings fancy application menu ($mod+d /F9 optional disabled)

bindsym $mod+d exec --no-startup-id rofi -modi drun -show drun \
		-config ~/.config/i3/rofi/rofidmenu.rasi
#bindsym $mod+d exec --no-startup-id i3-dmenu-desktop --dmenu="dmenu -nb '#1d2021' -nf '#ebdbb2' -sb '#d65d0e' -sf '#1d2021'"

#bindsym F9 exec --no-startup-id rofi -modi drun -show drun \
#		-config ~/.config/i3/rofi/rofidmenu.rasi

## rofi bindings for window menu ($mod+t /F10 optional disabled)

bindsym $mod+Tab exec --no-startup-id rofi -show window \
		-config ~/.config/i3/rofi/rofidmenu.rasi
#bindsym $mod+t exec --no-startup-id ~/.config/i3/scripts/i3-window-switch

#bindsym F10 exec --no-startup-id rofi -show window \
#		-config ~/.config/i3/rofi/rofidmenu.rasi

## keybinding helper (rofi)
bindsym $mod+Shift+question exec --no-startup-id ~/.config/i3/scripts/keybindings

## rofi bindings to manage clipboard (install rofi-greenclip from the AUR)

#exec --no-startup-id greenclip daemon>/dev/null
#bindsym $mod+c exec --no-startup-id rofi -modi "clipboard:greenclip print" -show clipboard \
#       -config ~/.config/rofi/rofidmenu.rasi

# Power Profiles menu switcher (rofi)
bindsym $mod+Shift+p exec --no-startup-id ~/.config/i3/scripts/power-profiles

###############################################################################
# Start Applications
###############################################################################

# bindsym $mod+Shift+Return exec thunar
# bindsym Ctrl+space exec --no-startup-id rofi -show run
# bindsym $alt+Tab exec --no-startup-id rofi -show window
# bindsym $mod+Ctrl+b exec terminal -e 'bmenu'

bindsym $mod+F1 exec dolphin
bindsym $mod+Shift+F1 exec pkexec dolphin
bindsym $mod+F2 exec firefox
bindsym $mod+Shift+F2 exec firefox --private-window
bindsym $mod+F5 exec brave --profile-directory='Default'
bindsym $mod+F6 exec brave --app=https://mail.google.com/mail/u/0/#inbox --profile-directory='Default'


# bindsym $mod+F3 exec dolphin
# bindsym $mod+F3 exec pcmanfm
# bindsym $mod+F3 exec ranger
# bindsym $mod+Shift+F3 exec gksu pcmanfm
# bindsym $mod+Shift+F3 exec gksu thunar
# bindsym $mod+F5 exec terminal -e 'mocp'
# bindsym $mod+t exec --no-startup-id pkill compton
# bindsym $mod+Ctrl+t exec --no-startup-id compton -b
# bindsym $mod+Shift+d --release exec "killall dunst; exec notify-send 'restart dunst'"
