cursor #dcd7ba
cursor_text_color #c8c093

foreground            #dcd7ba
background            #16161d
selection_foreground  #1f1f28
selection_background  #938aa9
url_color             #7fb4ca

color0   #1f1f28
color1   #e86892
color2   #65ca70
color3   #fcf371
color4   #6aa6bf
color5   #223249
color6   #7fb4ca
color7   #c7ccd4
color8   #4d5156
color9   #ff9fbe
color10  #9df2a7
color11  #fff9a5
color12  #98c9de
color13  #bcebff
color14  #d4f2ff
color15  #f8fbff
