cursor #c6d0f5
cursor_text_color #a5adce

foreground            #c6d0f5
background            #303446
selection_foreground  #303446
selection_background  #e5c890
url_color             #ef9f76

color0   #292c3c
color1   #ff7670
color2   #8cef76
color3   #ffe570
color4   #e38759
color5   #6d3e24
color6   #ef9f76
color7   #faf1eb
color8   #645e5b
color9   #ffa29e
color10  #b5ffa4
color11  #ffeea4
color12  #ffb691
color13  #ffc3a4
color14  #ffd8c4
color15  #fffaf8
