#!/usr/bin/env bash

# Don't run interactive stuff in non-interactive shells.
[[ $- != *i* ]] && return

source ~/.config/bash/aliases
source ~/.config/bash/functions
source ~/.config/bash/prompt

shopt -s autocd
shopt -s checkwinsize
shopt -s histappend

# machine-specific overrides
[[ -f ~/.config/bash/local ]] && source ~/.config/bash/local