#!/usr/bin/env bash

# vim: syntax=sh

# Don't run interactive stuff in non-interactive shells.
[[ $- != *i* ]] && return

source ~/.config/bash/aliases
source ~/.config/bash/functions
source ~/.config/bash/prompt

# Load shell completions
[[ -f "$HOME/.config/bash/completion" ]] && source "$HOME/.config/bash/completion"

# shopt
shopt -s autocd         # change to named directory
shopt -s cdspell        # autocorrects cd misspellings
shopt -s cmdhist        # save multi-line commands in history as single line
shopt -s dotglob
shopt -s expand_aliases # expand aliases
shopt -s checkwinsize   # updates LINES and COLUMNS on window resize
shopt -s globstar       # allows pattern "**" expands to recursively match all files and subdirectories
shopt -s histappend     # do not overwrite history

# avoid duplicates + ignore simple commands
HISTCONTROL=ignoreboth

# append instead of overwrite
shopt -s histappend

# I'm just used to this mode
set -o emacs

# disable Ctrl-S and Ctrl-Q because I keep pressing them by accident
stty stop ''
stty start ''
stty -ixon
stty -ixoff

# fzf history on Ctrl+R (override default reverse search)
#bind -x '"\C-r": fh'
bind -x '"\C-r": _fzf_history'

# source perlbrew
[[ -f "$HOME/perl5/perlbrew/etc/bashrc" ]] && source $HOME/perl5/perlbrew/etc/bashrc

# source rakubrew
[[ -f "$HOME/.rakubrew/bin/rakubrew" ]] && eval "$($HOME/.rakubrew/bin/rakubrew init Bash)"

# # -- START ACTIVESTATE INSTALLATION
# export PATH="/home/johnm/.komodoide/12.0/XRE/state/bin:$PATH"
# # -- STOP ACTIVESTATE INSTALLATION
# # -- START ACTIVESTATE DEFAULT RUNTIME ENVIRONMENT
# export PATH="/home/johnm/.cache/activestate/bin:$PATH"
# if [[ ! -z "$ACTIVESTATE_ACTIVATED" && -f "$ACTIVESTATE_ACTIVATED/activestate.yaml" ]]; then
#   echo "State Tool is operating on project $ACTIVESTATE_ACTIVATED_NAMESPACE, located at $ACTIVESTATE_ACTIVATED"
# fi
# # -- STOP ACTIVESTATE DEFAULT RUNTIME ENVIRONMENT

# kimi-code
export PATH="/home/johnm/.kimi-code/bin:$PATH"

# Added by Unsloth installer
export PATH="/home/johnm/.local/share/../bin:$PATH"

export PATH="$HOME/.npm-packages/node_modules/.bin:$PATH"

# machine-specific overrides
[[ -f ~/.config/bash/$(hostname).local ]] && source ~/.config/bash/$(hostname).local

# display system information
if [[ -f /usr/bin/fastfetch ]]; then
    fastfetch
fi
